### PR TITLE
Update urls

### LINKED ISSUE #5: Change links to GitLab
Next time there is a new version, we should take the opportunity to update the home and dev_url links in `meta.yaml` to point to GitLab instead of GitHub.

Creating this issue as a reminder :-)

### PR DESCRIPTION
**Pull request by cpascual**
Update urls (github->gitlab)

Fixes #5

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #5

### CODE REVIEW

**Comment by cpascual** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
Thanks for updating!
Note that you only have to update the `meta.yaml` file. The README is updated by the rerender command.

**Comment by cpascual** [comment]
> Note that you only have to update the meta.yaml file. The README is updated by the rerender command.

Yes, that's what I did. The README was updated automatically in 0d7529a

... but I noticed that the [conda-forge page in anaconda cloud still shows the old URLs](https://anaconda.org/conda-forge/taurus_pyqtgraph), even after [the new with the fixed meta.yml is uploaded](https://anaconda.org/conda-forge/taurus_pyqtgraph/files), and [PyPI metadata is also ok](https://pypi.org/project/taurus-pyqtgraph/).

@beenje , do you know if we need to change something else apart from meta.yml?

**Comment by beenje** [comment]
No, that's strange. I don't know how anaconda.org is updated (it's separate from conda-forge).
But this information must come from the package (about.json) and that's generated from the meta.yaml.

Maybe it's only updated for new version and not build number? (There is no build version mentioned on that page).

**Comment by cpascual** [comment]
ok. We''ll see if that is the case when we push higher version (which, BTW I expect will be automerged, since I activated it)

**Pull request merged**
